[package]
name = "bqti"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_bencode = "0.2.4"
serde_bytes = "0.11.19"
thiserror = "2.0.18"
sha1 = "0.10.6"
sha2 = "0.10.9"
hex = "0.4.3"
chrono = "0.4.44"
strum = { version = "0.27", features = ["derive"] }
either = "1.15.0"
clap = { version = "4", features = ["derive"] }
enum_dispatch = "0.3.13"
crossbeam = "0.8.4"
tracing = { version = "0.1.44", features = ["max_level_trace", "release_max_level_debug"] }
tracing-subscriber = { version = "=0.3.19", features = ["env-filter"] }
quinn = "0.11.9"
tokio = { version = "1.50.0", features = ["full"] }
async-trait = "0.1.89"
rustls = { version = "0.23.37", features = ["aws-lc-rs", "ring"] }
rustls-pki-types = "1.14.0"
rcgen = { version = "0.14.7", features = ["x509-parser"] }
futures = "0.3.32"
