[workspace]
members = ["bqti-ipc", "bqti-tee"]

[workspace.package]
version = "0.1.0"
description = "Bit Torrent with QUIC + TEE + I2P"
authors = ["Diogo Assunção"]
edition = "2024"
repository = "https://github.com/OnlyCavas/bqti"

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["full"] }
anyhow = "1.0.102"
tracing = { version = "0.1.44", features = ["max_level_trace", "release_max_level_debug"] }
tracing-subscriber = { version = "=0.3.20", features = ["env-filter"] }
futures = "0.3.32"
libc = "0.2.183"
ring = "0.17.14"
hex = "0.4.3"

[package]
name = "bqti"
version.workspace = true
edition.workspace = true

[features]
tee = ["dep:bqti-tee"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures.workspace = true
libc.workspace = true
ring.workspace = true
hex.workspace = true
bqti-ipc = { path = "bqti-ipc" }
serde_bencode = "0.2.4"
serde_bytes = "0.11.19"
sha1 = "0.10.6"
sha2 = "0.10.9"
chrono = "0.4.44"
strum = { version = "0.27", features = ["derive"] }
either = "1.15.0"
clap = { version = "4", features = ["derive"] }
enum_dispatch = "0.3.13"
crossbeam = "0.8.4"
quinn = "0.11.9"
tokio-util = "0.7.18"
async-trait = "0.1.89"
rustls = { version = "0.23.37", features = ["aws-lc-rs", "ring"] }
rustls-pki-types = "1.14.0"
rcgen = { version = "0.14.7", features = ["x509-parser"] }
directories = "6.0.0"
rand = "0.10.0"
indexmap = "2.13.0"
indicatif = "0.18.4"
console = "0.16.3"
base64 = "0.22.1"
data-encoding = "2.11.0"

[target.'cfg(target_arch = "riscv64")'.dependencies]
bqti-tee = { path = "bqti-tee", features = ["tee"], optional = true }
