[package]
name = "bqti-tee"
version.workspace = true
description.workspace = true
edition.workspace = true

[features]
tee = []

[build-dependencies]
cc = "1.0"

[dependencies]
libc = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
sha3 = "0.12.0"
curve25519-dalek = { version = "4.1.3", features = ["alloc"] }
tempfile = "3.27.0"
serde-big-array = "0.5.1"
