notransit = true
floodfill = false
bandwidth = L
share = 50

[http]
enabled = true
address = 0.0.0.0
port = 7070

[sam]
enabled = true
address = 0.0.0.0
port = 7656
udp = true
udpport = 7655

[limits]
transittunnels = 0

[exploratory]
inbound.length=0
inbound.quantity=1
outbound.length=0
outbound.quantity=1
